In [36]:
from utils.obj_func import sphere_function
from utils.surrogate import SingleTaskGP_rbf, SingleTaskGP_laplacian
from utils.expt_management import run_bo, run_expt

from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
from botorch.models import SingleTaskGP


%matplotlib inline
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# 1. 

In [18]:
# define exprimental settings
n_runs = 10
dim = 5
init_eval_num = 10
target_func = sphere_function
surrogate = SingleTaskGP


res_df = run_bo(n_runs, dim, init_eval_num, target_func, surrogate)
res_df

Iter: 1
tensor([[ 0.2875,  0.4098,  0.3041,  0.4046, -0.7070]], dtype=torch.float64)
New candidates: tensor([[ 0.2875,  0.4098,  0.3041,  0.4046, -0.7070]], dtype=torch.float64)
Current best y: 1.0048088674708744

Iter: 2
tensor([[ 0.4188,  0.9974,  0.0977,  0.1788, -0.4160]], dtype=torch.float64)
New candidates: tensor([[ 0.4188,  0.9974,  0.0977,  0.1788, -0.4160]], dtype=torch.float64)
Current best y: 1.0048088674708744

Iter: 3
tensor([[-0.1904,  0.3478,  0.0253,  0.4903, -0.8787]], dtype=torch.float64)
New candidates: tensor([[-0.1904,  0.3478,  0.0253,  0.4903, -0.8787]], dtype=torch.float64)
Current best y: 1.0048088674708744

Iter: 4
tensor([[-0.0844, -0.0116,  0.4361, -0.1695, -0.1050]], dtype=torch.float64)
New candidates: tensor([[-0.0844, -0.0116,  0.4361, -0.1695, -0.1050]], dtype=torch.float64)
Current best y: 0.23715914655844408

Iter: 5
tensor([[ 0.1316,  0.1438,  0.3119,  0.0282, -0.0052]], dtype=torch.float64)
New candidates: tensor([[ 0.1316,  0.1438,  0.3119,  0.028

評価点                   評価値  \
0   (0.9151307344436646, 0.3965124487876892, 0.612...              1.923843   
1   (0.4792305827140808, 0.2279067039489746, 0.943...              1.713504   
2   (0.7371718287467957, 0.8787279725074768, 0.614...              2.021346   
3   (0.060609281063079834, 0.6980960965156555, 0.8...              2.348853   
4   (0.8408638834953308, 0.3043971657752991, 0.921...              2.388347   
5   (0.4295172095298767, 0.22724640369415283, 0.81...              1.970047   
6   (0.25156551599502563, 0.7987673282623291, 0.57...              1.160231   
7   (0.1890236735343933, 0.7291653752326965, 0.143...              1.037143   
8   (0.8686277866363525, 0.18954992294311523, 0.34...              1.004809   
9   (0.5520549416542053, 0.7577236890792847, 0.145...              1.921061   
10  (0.2875292878597975, 0.409785233438015, 0.3041...    1.0066210862896652   
11  (0.41878111846745014, 0.9973721373826265, 0.09...    1.3846693517243815   
12  (-0.19038752280175686, 0.3477756306529045, 0.0...    1.1704275436388356   
13  (-0.0844060517847538, -0.011611653491854668, 0...   0.23715914655844408   
14  (0.1316049299960787, 0.143840672017907, 0.3119...   0.13611783563982865   
15  (-0.10577601757237198, 0.2311923418930358, 0.3...   0.22891161138029967   
16  (-0.027183067618742625, -0.10727569997121449, ...    0.2148425387362471   
17  (0.17487759974121161, -0.09195948000909125, 0....   0.13992296028029408   
18  (-0.0901671856690227, -0.037715029258424834, 0...  0.011548701199749127   
19  (0.05958375625334518, 0.047693939782590095, 0....   0.03427551136297578   

         最適値  
0        NaN  
1        NaN  
2        NaN  
3        NaN  
4        NaN  
5        NaN  
6        NaN  
7        NaN  
8   1.004809  
9        NaN  
10  1.004809  
11  1.004809  
12  1.004809  
13  0.237159  
14  0.136118  
15  0.136118  
16  0.136118  
17  0.136118  
18  0.011549  
19  0.011549

In [20]:
res_df.min()

評価点    (-0.19038752280175686, 0.3477756306529045, 0.0...
評価値                                 0.011548701199749127
最適値                                             0.011549
dtype: object

0.011548701199749127

In [30]:
import os

# working_dir = './expts_result/'

working_dir = f'./expts_result/'


# define exprimental settings
n_runs = 10
dim = 5
init_eval_num = 10
target_func = sphere_function
surrogate = SingleTaskGP

dim_subdir = f'{dim}_dim'

save_dir = os.path.join(working_dir, dim_subdir)

if not os.path.exists(save_dir):
    os.makedirs(save_dir)


accumulated_loss = 0
target_value = 0

bo_num = 10

for i in range(bo_num):
    res_df = run_bo(n_runs, dim, init_eval_num, target_func, surrogate)
    accumulated_loss += abs(target_value - res_df['最適値'].min())
    save_path = os.path.join(save_dir, f'opt_{i+1}.csv')
    res_df.to_csv(save_path)

print(f'総損失: {accumulated_loss}')

# 設定を辞書として定義
settings = {
    'n_runs': n_runs,
    'dim': dim,
    'init_eval_num': init_eval_num,
    'target_func': str(target_func),
    'surrogate': str(surrogate),
    'accumulated_loss': surrogate,
    'target_value': target_value,
    'bo_num': bo_num
}

# 設定をテキストファイルに保存
settings_file_path = os.path.join(save_dir, 'settings.txt') 
with open(settings_file_path, 'w') as f:
    for key, value in settings.items():
        f.write(f'{key}: {value}\n')

Iter: 1
tensor([[ 0.9297,  0.5987,  0.5575, -0.5599,  0.6573]], dtype=torch.float64)
New candidates: tensor([[ 0.9297,  0.5987,  0.5575, -0.5599,  0.6573]], dtype=torch.float64)
Current best y: 1.18938465298746

Iter: 2
tensor([[ 0.2273, -0.0348,  0.3729,  0.2088,  0.9385]], dtype=torch.float64)
New candidates: tensor([[ 0.2273, -0.0348,  0.3729,  0.2088,  0.9385]], dtype=torch.float64)
Current best y: 1.116367205957807

Iter: 3
tensor([[-0.1498, -0.0979,  0.5672,  0.3268,  0.2932]], dtype=torch.float64)
New candidates: tensor([[-0.1498, -0.0979,  0.5672,  0.3268,  0.2932]], dtype=torch.float64)
Current best y: 0.5464895735543145

Iter: 4
tensor([[0.1251, 0.1341, 0.4113, 0.1429, 0.3257]], dtype=torch.float64)
New candidates: tensor([[0.1251, 0.1341, 0.4113, 0.1429, 0.3257]], dtype=torch.float64)
Current best y: 0.3292642886151742

Iter: 5
tensor([[-0.0377,  0.0045,  0.5978, -0.0783,  0.4372]], dtype=torch.float64)
New candidates: tensor([[-0.0377,  0.0045,  0.5978, -0.0783,  0.4372]], 

In [24]:
import os


In [25]:
path = f'expts_result/{dim}_dim/'

path

'expts_result/5_dim/'

In [27]:
str(surrogate)

"<class 'botorch.models.gp_regression.SingleTaskGP'>"

In [37]:
# define exprimental settings
n_runs = 10
dim = 6
init_eval_num = 10
target_function = sphere_function
surrogate = SingleTaskGP

run_expt(n_runs, dim, init_eval_num, target_function, surrogate)

Iter: 1
tensor([[ 0.1848,  0.3317, -0.0711,  0.2919,  0.4202,  0.2038]],
       dtype=torch.float64)
New candidates: tensor([[ 0.1848,  0.3317, -0.0711,  0.2919,  0.4202,  0.2038]],
       dtype=torch.float64)
Current best y: 0.45255539008988555

Iter: 2
tensor([[ 0.1396,  0.3436, -0.1622,  0.3832,  0.1081,  0.0701]],
       dtype=torch.float64)
New candidates: tensor([[ 0.1396,  0.3436, -0.1622,  0.3832,  0.1081,  0.0701]],
       dtype=torch.float64)
Current best y: 0.32723513456968795

Iter: 3
tensor([[ 0.1591,  0.2307, -0.1568,  0.3301,  0.3737, -0.1308]],
       dtype=torch.float64)
New candidates: tensor([[ 0.1591,  0.2307, -0.1568,  0.3301,  0.3737, -0.1308]],
       dtype=torch.float64)
Current best y: 0.32723513456968795

Iter: 4
tensor([[ 0.0916,  0.2176,  0.0731,  0.2167,  0.1352, -0.0153]],
       dtype=torch.float64)
New candidates: tensor([[ 0.0916,  0.2176,  0.0731,  0.2167,  0.1352, -0.0153]],
       dtype=torch.float64)
Current best y: 0.12656200082191704

Iter: 5
tens

In [38]:
original_string = "<class 'botorch.models.gp_regression.SingleTaskGP'>"

# 最初に ' を探す
start_index = original_string.rfind("'") + 1

# 最後に ' を探す
end_index = original_string.rfind("'", start_index)

# 名前を取り出す
name = original_string[start_index:end_index]

print(name)


In [39]:
original_string

"<class 'botorch.models.gp_regression.SingleTaskGP'>"

In [43]:
original_string.rfind("'")

49

In [40]:
original_string.rfind('.')

36

In [41]:
original_string[36]

'.'

In [44]:
original_string[37:49]

'SingleTaskGP'

In [45]:
target_function

<function utils.obj_func.sphere_function(x)>

In [46]:
from botorch.test_functions import Ackley

In [48]:
f = Ackley(dim=2)

In [49]:
f

Ackley()

In [50]:
f.evaluate_true

<bound method Ackley.evaluate_true of Ackley()>

In [53]:
import torch
x = torch.rand(10,2)
x

tensor([[0.4702, 0.9378],
        [0.2243, 0.6371],
        [0.7718, 0.2370],
        [0.7751, 0.0033],
        [0.0381, 0.1681],
        [0.9820, 0.4351],
        [0.1313, 0.4867],
        [0.5085, 0.7365],
        [0.6445, 0.3149],
        [0.5105, 0.4505]])

In [54]:
f.evaluate_true(x)

tensor([4.5045, 3.7577, 3.7611, 3.0116, 1.1210, 4.4982, 3.2412, 4.5143, 4.0446,
        4.1770])

In [55]:
from botorch.models import SingleTaskGP

In [57]:
str(SingleTaskGP)

"<class 'botorch.models.gp_regression.SingleTaskGP'>"