In [3]:
import torch
from utils.kernel import dist, sq_dist
from gpytorch.kernels.kernel import dist as dist_original
from gpytorch.kernels.kernel import sq_dist as sq_dist_original

In [5]:
x1 = torch.rand(2, 3, 4)
y1 = torch.rand(2, 3, 4)

x1, y1

(tensor([[[0.6127, 0.4604, 0.5398, 0.0479],
          [0.6128, 0.0878, 0.3905, 0.8656],
          [0.2046, 0.2141, 0.0952, 0.0953]],
 
         [[0.9897, 0.5021, 0.6115, 0.1162],
          [0.1772, 0.9120, 0.5050, 0.6552],
          [0.0468, 0.7313, 0.2049, 0.5569]]]),
 tensor([[[0.0174, 0.9005, 0.6092, 0.0043],
          [0.3693, 0.5592, 0.6206, 0.2233],
          [0.7818, 0.3198, 0.4800, 0.3435]],
 
         [[0.4742, 0.2689, 0.6255, 0.6547],
          [0.5971, 0.8579, 0.1799, 0.1350],
          [0.2163, 0.7557, 0.5295, 0.5905]]]))

In [8]:
dist_original(x1, y1).shape, dist_original(x1, y1)

(torch.Size([2, 3, 3]),
 tensor([[[0.7449, 0.3260, 0.3732],
          [1.3434, 0.8643, 0.6024],
          [0.8824, 0.6623, 0.7443]],
 
         [[0.7813, 0.6836, 0.9456],
          [0.7186, 0.7453, 0.1754],
          [0.7636, 0.7053, 0.3685]]]))

In [10]:
dist(x1, y1).shape, dist(x1, y1)

(torch.Size([2, 2, 3]),
 tensor([[[1.1485, 1.5874, 1.3159],
          [1.0226, 1.7270, 1.4827]],
 
         [[1.4849, 1.0924, 1.6351],
          [1.3014, 1.3192, 0.5520]]]))

In [13]:
from torchmetrics.functional.pairwise import pairwise_manhattan_distance 

In [11]:
import torch

def dist_3d(x1, x2, x1_eq_x2=False):
    x1 = x1.unsqueeze(2)
    x2 = x2.unsqueeze(1)
    distance = torch.abs(x1 - x2).sum(dim=-1)
    return distance.clamp_min_(0)


In [ ]:
x1 = 

In [12]:
dist_3d(x1, y1)

tensor([[[1.1485, 0.5984, 0.6650],
         [2.4881, 1.5874, 1.0126],
         [1.4786, 1.1631, 1.3159]],

        [[1.3014, 1.1988, 1.5833],
         [1.0612, 1.3192, 0.2846],
         [1.4083, 1.1238, 0.5520]]])

In [15]:
dist_original(x1, y1)

tensor([[[0.7449, 0.3260, 0.3732],
         [1.3434, 0.8643, 0.6024],
         [0.8824, 0.6623, 0.7443]],

        [[0.7813, 0.6836, 0.9456],
         [0.7186, 0.7453, 0.1754],
         [0.7636, 0.7053, 0.3685]]])

In [23]:
x1.ndim

3

In [16]:
x2 = torch.rand(2,4)
y2 = torch.rand(2,4)

In [17]:
dist(x2, y2)

tensor([[1.5857, 2.2379],
        [0.6135, 1.3398]])

In [18]:
pairwise_manhattan_distance(x2,y2)

tensor([[1.5857, 2.2379],
        [0.6135, 1.3398]])

In [19]:
dist_3d(x2, y2)

tensor([[0.9179, 1.5138, 1.8496, 1.0990],
        [1.2217, 1.4865, 2.4927, 1.9908]])

In [20]:
torch.cdist(x2, y2, p=1)

tensor([[1.5857, 2.2379],
        [0.6135, 1.3398]])

In [21]:
torch.cdist(x1, y1, p=1)

tensor([[[1.1485, 0.5984, 0.6650],
         [2.4881, 1.5874, 1.0126],
         [1.4786, 1.1631, 1.3159]],

        [[1.3014, 1.1988, 1.5833],
         [1.0612, 1.3192, 0.2846],
         [1.4083, 1.1238, 0.5520]]])

In [22]:
dist_3d(x1, y1)

tensor([[[1.1485, 0.5984, 0.6650],
         [2.4881, 1.5874, 1.0126],
         [1.4786, 1.1631, 1.3159]],

        [[1.3014, 1.1988, 1.5833],
         [1.0612, 1.3192, 0.2846],
         [1.4083, 1.1238, 0.5520]]])